### PR TITLE
core: add snapshot-site arg to support the northwestern snap site

### PR DESCRIPTION
**Pull request by Bogdanp**

### CODE REVIEW

**Comment by Bogdanp** [comment]
@rfindler would you be able to add symlinks for BC Linux snapshots w/o the Linux distro in the name?

These BC URLs currently fail:

* https://plt.cs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-bc.sh
* https://plt.cs.northwestern.edu/snapshots/current/installers/racket-minimal-current-x86_64-linux-bc.sh

But these CS URLs work fine:

* https://plt.cs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-cs.sh
* https://plt.cs.northwestern.edu/snapshots/current/installers/racket-minimal-current-x86_64-linux-cs.sh

**Comment by mflatt** [comment]
At the Northwestern site, the Ubuntu builds are 64-bit CS and 32-bit BC. The 64-bit BC build is on Debian, where `(list #f "" #f)` is not included in `#:dist-aliases`. (Note that you don't want to include the other one there, `(list #f #f "")`, because you want the result name to refer to the Ubuntu build).

Clarification on the `current` links: special treatment of the first alias is about which one is linked from "as current" on the web page, but `current` file names are created for all aliases. I'll adjust the docs to make that more clear.

**Comment by rfindler** [comment]
🤦  Thanks for getting this sorted out. I was really barking up the wrong tree!

Okay, so I'll try adding a 64bit BC build and also adding a set of builds that don't have main-distribution-test (or the other pkgs), but instead just main-distribution, hopefully with the same names as on the utah site.

**Comment by Bogdanp** [comment]
> Thanks for looking into this! One idea I had after opening the issue was to have your CI code check to see which snapshot build has completed more recently and use that (by default; letting people opt in to sticking with a specific snapshot site if they need to). Generally speaking, I think that both sites have gotten pretty reliable, but when one of them has trouble, the other one tends to be working.

I think this is a good idea, but I'll need some more help from the snapshot sites to implement the recency check. Ideally, there would be a structured file (JSON would be easiest for this action) with metadata about the build so I have something to compare between the two. For now, I've changed `snapshot_site` to default to `auto`, and it will [select the first live snapshot site, preferring Utah](https://github.com/Bogdanp/setup-racket/pull/64/files#diff-1f963b5ae3613de37b5354a3da594cdef878e0715ad0eb3896bd701e2511b273R401-R426).

**Comment by rfindler** [comment]
> I think this is a good idea, but I'll need some more help from the snapshot sites to implement the recency check.

How about comparing the contents of this file: https://plt.cs.northwestern.edu/snapshots/current/stamp.txt to https://users.cs.utah.edu/plt/snapshots/current/stamp.txt ?

**Comment by Bogdanp** [comment]
That works! I've pushed a change to use that file. I think once the build changes are ready on the Northwestern side, this is good to go.

**Comment by rfindler** [comment]
> I think once the build changes are ready on the Northwestern side, this is good to go.

The first attempt at the build with the new configuration completed and I got the configuration wrong, sadly.  I think I see what I did wrong and I've fixed the configuration; hopefully the next time we'll get all the builds we need.

**Comment by rfindler** [comment]
It looks like the build completed successfully this time. There are various aliases too, but here are the names of the builds that I think that the CI wants to use:

```
racket-current-x86_64-linux-bc.sh
racket-current-x86_64-linux-cs.sh
racket-current-i386-linux-bc.sh

racket-minimal-current-i386-linux-bc.sh
racket-minimal-current-x86_64-linux-bc.sh
racket-minimal-current-x86_64-linux-cs.sh
```

Does that look right? Am I missing any?

----

Also, it occurs to me that sometimes, when builds fail, the relevant file just won't be there, even though the rest of the site will be. So it probably makes sense to use the `stamp.txt` file to disambiguate between builds specifically when the file exists on both sites. At least at northwestern, from time to time, one of the VMs acts up and needs to be rebooted; the rest of the build might complete fine in that situation and there might be a stamp.txt file generated, but some specific files just won't be there (this happened with the debian builds at northwestern last night).

**Comment by Bogdanp** [comment]
> Does that look right? Am I missing any?

It looks like these are still missing:

* https://plt.cs.northwestern.edu/snapshots/current/installers/racket-current-x86_64-macosx-bc.dmg
* https://plt.cs.northwestern.edu/snapshots/current/installers/racket-current-x86_64-macosx-cs.dmg
* https://plt.cs.northwestern.edu/snapshots/current/installers/racket-current-x86_64-win32-bc.exe
* https://plt.cs.northwestern.edu/snapshots/current/installers/racket-current-x86_64-win32-cs.exe

>  Also, it occurs to me that sometimes, when builds fail, the relevant file just won't be there, even though the rest of the site will be. So it probably makes sense to use the stamp.txt file to disambiguate between builds specifically when the file exists on both sites. At least at northwestern, from time to time, one of the VMs acts up and needs to be rebooted; the rest of the build might complete fine in that situation and there might be a stamp.txt file generated, but some specific files just won't be there (this happened with the debian builds at northwestern last night).

That makes sense. I'll update the code to issue head requests for the files in addition to the stamps.

**Comment by rfindler** [comment]
Okay, it looks like things worked and we've got those four builds on the northwestern snapshot site now.

**Comment by Bogdanp** [comment]
Yup! Everything looks good now. Thanks for all your help and suggestions!

**Comment by rfindler** [comment]
Thank you for making these changes! Hopefully the northwestern site will be
more useful to folks and and CI will have a bit more redundancy.

**Pull request merged**
